version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  build:
    commands:
      - ./gradlew bootJar
  post_build:
    commands:
      - echo Build completed
artifacts:
  files:
    - app/build/libs/app*SNAPSHOT.jar
    - scripts/server/*.sh
    - appspec.yml
    - amazon-cloudwatch-agent.json
  discard-paths: yes

