name: infrastructure
on:
  push:
    branches:
      - 'main'
    paths:
      - 'infrastructure/src/main/**'
      - 'infrastructure/src/build.gradle.kts'
      - 'scripts/ec2/**'
      - 'cdk.json'
      - '.github/workflows/deploy-infrastructure.yml'

jobs:
  log-diff:
    runs-on: 'ubuntu-latest'
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: 'gradle'
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Install Python dependencies and CDK
        run: |
          python -m pip install --upgrade pip
          # install your Python dependencies here
          npm install -g aws-cdk
      - name: Configure AWS credentials for read role
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_READ_ROLE }}
          aws-region: ap-southeast-2
          role-session-name: log-diff@githubactions
      - name: Download dependencies
        run: |
          ./gradlew build
      - name: CDK synth
        shell: bash
        run: |
          cdk synth || true
      - name: Run diff
        run: cdk diff --app infrastructure/cdk.out

  deploy-prod:
    runs-on: 'ubuntu-latest'
    environment: 'prod'
    needs: log-diff
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: 'gradle'
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Install Python dependencies and CDK
        run: |
          python -m pip install --upgrade pip
          # install your Python dependencies here
          npm install -g aws-cdk
      - name: Configure AWS credentials from test env
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE }}
          aws-region: ap-southeast-2
          role-session-name: deploy-dev@githubactions
      - name: Download dependencies
        run: |
          ./gradlew build
      - name: CDK synth
        shell: bash
        run: |
          cdk synth || true
      - name: Deploy stacks
        run: cdk deploy --app infrastructure/cdk.out --require-approval never --all
